### ISSUE TITLE
Table borders in Network's request list

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#109]
Came up in https://bugzilla.mozilla.org/show_bug.cgi?id=1416714#c27 with patches attached.

![image](https://user-images.githubusercontent.com/8599/74074069-780f3600-49c1-11ea-85ae-dca860b4bc98.png)

I wanted to file this issue to discuss the border idea as it might be something we want to continue. I find it a bit easier to scan the table on my large 4k screen. Profiler's tables (and Storage) also use the same border pattern.

cc @bomsy @violasong @janodvarko

**Comment by fvsch** [comment]
Screenshot with the current UI and using a `--theme-splitter-color` border (at 2x resolution):

![Screenshot](https://user-images.githubusercontent.com/243601/74140156-d708c100-4bf4-11ea-85b5-ceef6b73e057.png)

I kinda like it.

**Comment by janodvarko** [comment]
Looks great to me.

Honza

**Comment by bomsy** [comment]
Same i like it.

**Comment by bomsy** [comment]
Tried it with dark theme as well ..

![Screenshot](https://user-images.githubusercontent.com/792924/74165499-7d6cba80-4c25-11ea-9a43-d81b6d3082c8.png)

**Comment by violasong** [comment]
This does look good! Could you try a bit more left/right padding on the columns? I know it takes space to do this, but I still think our horizontal spacing issues should be solved via tighter spacing on the columns with less text.

A tangent, but I was just looking at Finder and Chrome and now I'm wondering if we should be right-aligning our transferred and size columns.

**Comment by fvsch** [comment]
I opened [bug 1614567](https://bugzilla.mozilla.org/show_bug.cgi?id=1614567) and I'll have a patch ready for review shortly.

Screenshots at 2x resolution:

- [network-monitor-requests-borders1-dark](https://user-images.githubusercontent.com/243601/74225356-d4709f00-4cba-11ea-8792-f2c373668c03.png)
- [network-monitor-requests-borders1-light](https://user-images.githubusercontent.com/243601/74225362-d8042600-4cba-11ea-9ca9-3dbddd17d212.png)
- [network-monitor-requests-borders2-dark](https://user-images.githubusercontent.com/243601/74225364-d9355300-4cba-11ea-81a8-6bad4d15db51.png)
- [network-monitor-requests-borders2-light](https://user-images.githubusercontent.com/243601/74225367-daff1680-4cba-11ea-84a3-7be8526b47d3.png)

What I did:

- Border color: I'm using our standard `--theme-splitter-color` in the headers, but in the table body I'm using a custom variable that is a bit more subtle in the light theme and identical to `--theme-splitter-color` in the dark theme (because the dark theme splitter color is already very subtle).
- Padding: our current padding is 4px of padding-left (total space between two columns = 4px). I used `padding-left: 5px; padding-right: 4px` (total space between two columns = 10px with the border), which felt generous and balanced enough.
- Borders are hidden (transparent) for hovered and selected rows. I felt it looked cleaner with the light blue/dark blue backgrounds, and we barely notice it (it's kind of like those visual illusions where our brains fill in the blanks). The borders for the top and bottom rows already suggest the table structure.
- For cached requests, I moved away from `td { opacity: 0.7 }` because it altered the border color as well. So now cached requests use our standard medium gray text color (the one we use for code comments), and only icons use `opacity: 0.7`.

**Comment by fvsch** [comment]
@violasong @digitarald Patch is in good shape and accepted. You can use the screenshots in the previous comment for the UI review.

**Comment by digitarald** [comment]
@fvsch thanks for working on this and the code polish on top of it! I added my LGTM to the patch.

**Comment by violasong** [comment]
LGTM as well - thanks!

**Comment by fvsch** [comment]
Landed in the latest Nightly.
