### ISSUE TITLE
Clarify disabled-pausing state

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#125]
We did some work, like fading out the breakpoint panels, to ensure disabled pausing is clearly communicated.

Seeing reports like https://twitter.com/__jakub_g/status/1260912327702073347 there is more work to do it seems.

Thoughts:
- Is it just an expectation to look for icons users might be more used to, like Chrome's; then we should just get closer to that icon shape/color
- As part of ["footgun indicator"](https://github.com/firefox-devtools/ux/issues/60) discussion, we shared mockups of "Pausing is disabled" warning bar similar to the "Debugger is paused"

cc @violasong @darkwing @fvsch @janodvarko

**Comment by violasong** [comment]
Here's the mockup of the warning bar: https://github.com/firefox-devtools/debugger/issues/6673#issuecomment-623780401

**Comment by fvsch** [comment]
Personally I don't find Chrome's icon a good solution.
Pros: there's a clear distinction between the two states because the shape of the icon changes, not just its color.
Cons: a blue breakpoint does not convey "Breakpoints are currently disabled" to me, at all.

Chrome, breakpoints enabled:
![Screenshot](https://user-images.githubusercontent.com/243601/82026850-9b6a1100-9693-11ea-8a71-90b02e259029.png)

Chrome, breakpoints disabled:
![Screenshot](https://user-images.githubusercontent.com/243601/82026796-88efd780-9693-11ea-9bb8-a3bd497cdca7.png)

IMO we should:

1. Revise our icon states, but not follow Chrome. We talked about using red for the "on" state of buttons that disable stuff (like the "Request Blocking" icon in Network's toolbar).
2. Add a warning bar, implementing Victoria's design.
3. Optionally and like Victoria suggested, remove the graying of pane content because its raison d'être has been superceded by (1) and (2).

**Comment by violasong** [comment]
Some quick sketches
<img width="146" alt="image" src="https://user-images.githubusercontent.com/55994/82256564-6d8f0180-990b-11ea-9b81-c1d2da8fddfb.png">
<img width="135" alt="image" src="https://user-images.githubusercontent.com/55994/82256615-813a6800-990b-11ea-9685-da7a736167cb.png">
<img width="143" alt="image" src="https://user-images.githubusercontent.com/55994/82256681-a5964480-990b-11ea-82b0-fca95da21ed3.png">
<img width="135" alt="image" src="https://user-images.githubusercontent.com/55994/82256857-ebeba380-990b-11ea-88ef-21551e150b8c.png">

I think I actually like the blue one on top best because it's a simple on-off of this button. The red introduces an extra layer of confusion because it begins to illustrate the double negative of 'stopping the stops.'

**Comment by digitarald** [comment]
> I think I actually like the blue one on top best because it's a simple on-off of this button.

fwiw, request blocking goes also blue.

The struggle is real to have an _enabled_ state for a _disabling_ button. Apart from the strike and the color change, would an _enabled_ button background add context?

**Comment by violasong** [comment]
Ah yes! That background would be good

<img width="153" alt="image" src="https://user-images.githubusercontent.com/55994/82371883-cc1db380-99cf-11ea-9c7f-f1e65b6bc300.png">

**Comment by darkwing** [comment]
I love those two!

**Comment by digitarald** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1643130 and opened it up as `good-first-bug` 👋🏻

**Comment by violasong** [comment]
Closing since this graduated to bugzilla :)
