### ISSUE TITLE
Improve Debugger empty UI links

### ISSUE THREAD

**Issue by violasong** [firefox-devtools/ux#29]
See [this bug](https://github.com/devtools-html/debugger.html/pull/6917#issuecomment-419353866) for potential concerns about the understated look of the shortcut info/'links' when no tabs are open. Should we simply apply the [photon ghost button](https://design.firefox.com/photon/components/buttons.html) styling, or is there a better solution here?

**Comment by yogmel** [comment]
I've been thinking for a while...that's not an easy question. As you mentioned in the conversation, I suppose it depends on this question:

How important is that the user knows that text is clickable?
    a. _Very important_: make the button very obviously clickable, by changing the **color** of the text, its background color or insert an **underline**.

    b. _It is good to know_: maybe insert the **photon ghost button** of the New icon.

    c. _Not important, surprise them_: a more showy **hover state**, such as changing the background color or the color to a brighter/different one.

This is hard, because all of these options would change the actual design which already looks perfect. 
In any way, I agree with you, I don't believe making them button-like links is a solution.
-----

What do you think? I can try working on some mockups to show them here.

**Comment by violasong** [comment]
@yogmel Sorry for the extremely late reply! I think you made great points here.

I think this UI may have changed since this bug was filed? In any case, I think the current bolded shortcut with subtle text hover effect is probably fine for now. I'm more bothered by the fact that it's not vertically aligned ;) so I'll file a bug for that.
