### ISSUE TITLE
Console Row Borders

### ISSUE THREAD

**Issue by mcroud** [firefox-devtools/ux#42]
To improve the legibility of a busy console containing many messages, row borders should be explored to provide a clear divider between individual logs and warnings.

Iteration 1 created by @fvsch:

> - 1px borders using the splitter color (we probably want different colors for navigation, errors and warnings);
> - 15px line-height for the text (11px font-size), as discussed with Victoria for the markup view;
> - 2px padding, which makes the single-line rows 19px tall, and 20px tall if we count the top border. 

![screen_shot_2018-12-12_at_19 18 59](https://user-images.githubusercontent.com/42435754/50078561-392b8900-01df-11e9-9937-375493df9be4.png)

![screen_shot_2018-12-12_at_19 19 59](https://user-images.githubusercontent.com/42435754/50078679-7f80e800-01df-11e9-9c4b-08ae36b3c60a.png)

Current feedback is positive for the dark theme mockup and the light theme mockup with grey 20 (pictured above).

Another discussion was around the inclusion of a setting to toggle line seperators, feedback on this idea highlighted that more settings can increase the likelihood of bugs and so should be considered carefully.

The next steps would be to produce visuals presenting these line seperators on a busy console, depicting a variety of different messages and log types.

@fvsch Did I forget anything? :)

**Comment by fvsch** [comment]
That sounds like everything.

I tried it in code, and here is an example on a busy console with errors and warnings:

Test with red/yellow borders for errors and warnings (I used the text color at 25% opacity):

![console-borders-colors](https://user-images.githubusercontent.com/243601/50094290-292d9c80-0213-11e9-80a8-0f2909e9c182.png)

Test with the same Grey 20 border for everything:

![console-borders-gray2](https://user-images.githubusercontent.com/243601/50094337-495d5b80-0213-11e9-98fb-0191c1ed9003.png)

Same, but using the splitter color (Grey 25) for borders of errors and warnings:

![console-borders-gray1](https://user-images.githubusercontent.com/243601/50094361-55e1b400-0213-11e9-9e93-5146707e9da9.png)

Overall I'm not 100% happy with it, I find that the borders and background colors compete for attention a bit. Looking at what Chrome DevTools do, they have the same problem to some extent, but they use very light colors for console row borders (e.g. closer to a "Grey 15" than the Grey 20 for normal rows).

If we think this will help usability, I guess we can take a small "prettiness" hit.

**Comment by digitarald** [comment]
Personally, I like the gray borders as it seems less noisy – the additional contrast for errors/warnings is a great touch to improve contrast. But it is a tough call.

@mcroud would it make sense to tweet this out to gather some feedback?

**Comment by violasong** [comment]
Tweeted :)

I think the colored borders look great, but maybe could use less opacity to match the gray a little more? Let's see what people say.

**Comment by fvsch** [comment]
Looking at the replies to https://mobile.twitter.com/FirefoxDevTools/status/1076202797429710848 both options are popular, but it seems the colored borders have a slight lead.

> I think the colored borders look great, but maybe could use less opacity to match the gray a little more

We can try that.

@nchevobbe I have a small implementation question. One way to handle borders is to have top and bottom borders for each row, and overlap rows by 1px (`.message { position: relative; margin-top: -1px }`). Do you think this could have a perf impact? It's much easier to deal with borders that way, because we don't have do have a bunch of selectors like this:

```css
.message.error,
.message.error + .message {
  border-top-color: red;
}
```

**Comment by nchevobbe** [comment]
I don't know from the top of my head if there could be a perf impact, but we can run damp to make sure there is not.

**Comment by dholbert** [comment]
@digitarald pinged me to ask about this -- I don't think there'd be a perf impact to adding borders & using this `margin-top` hack.

Though, one minor correction RE this hypothetical styling...
`.message { position: relative; margin-top: -1px }`

If you're just using `margin-top` for the adjustment, then you probably don't need `position:relative`.  You would only need `position:relative` if you were using `top` (rather than `margin-top`) to make the tweak, I think.

**Comment by digitarald** [comment]
Implementation tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1519904

**Comment by fvsch** [comment]
The borders create a few design challenges.

Ideally, we want an error message to show two red borders (top and bottom), and warning message to show two yellow borders, etc. This creates issues with:

1. Borders between two messages (we want only one border)
2. The top border of the first message (clashes with the toolbar's border)
3. The bottom border of the last message (clashes with the input area's top border)

For (1), I'm showing errors and warnings above ordinary messages, so that the error/warning border takes precedence. When a warning follows an error or the other way round, the second item's top border takes precedence (so we get "red, yellow, yellow" for error+warning). We could decide that errors always overtake warnings ("red, red, yellow"), but in my tests it didn't look particularly better.

For (2), I'm removing the top border of the first message. Chrome does it differently: it puts a 1px gap between the toolbar and the first message, but this did not look better IMO.

For (3), Ideally the input area wouldn't have a border, so we would show the bottom border of the last message (whether it's light gray, red or yellow). This is what Chrome does and it looks good. BUT, when the logs are longer than the output area, we keep the input area fixed to the bottom, and it needs a top border to be clearly visible. Chrome doesn't do that: the input area scrolls way with the rest of the console content, which is not great. So for now I'm keeping the input area's top border (gray), and removing the bottom border of the last message. It's a trade-off. This is how it looks:
![screen shot](https://user-images.githubusercontent.com/243601/51182560-e40e9000-18ce-11e9-82fa-8ad060bc47a1.png)

Finally, I'm wondering how to show the navigation messages:

- A: Use the default subtle borders (same as normal logs), errors/warnings take precedence
![screen shot](https://user-images.githubusercontent.com/243601/51182290-f4723b00-18cd-11e9-9667-a5a219b091d5.png)

- B: Use a blue border with somewhat high contrast (I'm using our "Blue 30", which is more contrasted that the red and yellow shades I'm using for error/warning borders), and navigation messages take precedence over errors and warnings
![screen shot](https://user-images.githubusercontent.com/243601/51182378-43b86b80-18ce-11e9-9de0-de92c978a112.png)

- C: Use a lighter blue border and put navigation logs at the z-index as errors and warnings
![screen shot](https://user-images.githubusercontent.com/243601/51182490-ab6eb680-18ce-11e9-8986-e048b63cb199.png)

**Comment by fvsch** [comment]
You can download [a Nightly build for macOS with console row borders here](https://queue.taskcluster.net/v1/task/Nick38Z_TBmHS36BRhC9UA/runs/0/artifacts/public/build/target.dmg).
/cc @violasong @mcroud

**Comment by digitarald** [comment]
I like how highlights the errors and warnings; this feels like the right balance and intention of raising importance of severe messages while visually differentiating.

**Comment by fvsch** [comment]
@nchevobbe Since you piloted the work on making the navigation marker more visible, do you think A would work (error and warning borders take over) or would you rather use something like B (navigation borders take over)?

**Comment by nchevobbe** [comment]
Great work Florens!

For navigation message I really like `B`, as it stands out from the other messages, which is what we want.

**Comment by mcroud** [comment]
@fvsch Your initial 3 points and your suggestions to overcome them seem well considered and logical to me 👍  Having errors/warnings take precedence aligns with my hierarchy of message importance which is why image A felt like a good balance to me.

It's tricky to determine whether something stands out adequately given the 100 billion combiniations of console output 😆  but even when the Navigation messages are sandwiched between two red errors, that crisp blue globe icon still stands out (for me at least).

Perhaps I am not aware of the true importance of the Navigation message and its position in the hierarchy, B certainly frames them with a greater importance and if they need to take front and center then B succeeds in doing that.

**Comment by violasong** [comment]
I like A/C best, and agree with @mcroud that maybe there's some importance to the navigation message that I'm not fully groking. I think B just looks a bit too strong, since we don't currently use that bright outline look anywhere - maybe C works as a middle ground?

**Comment by violasong** [comment]
Oh, what if B, but with the lighter blue outline colors of C?

If it needs more prominence beyond that, there's other things we could try with bolding, etc

**Comment by digitarald** [comment]
> Navigation message

Important to keep in mind that a) they act more as separators than actual messages and b) they only show up for a subset of users that enable `Persist Logs`.

**Comment by fvsch** [comment]
This landed in Firefox 68 (beta).
