### ISSUE TITLE
Fixing vertical (and horizontal) rhythm in debugger right sidebar

### ISSUE THREAD

**Issue by jaril** [firefox-devtools/ux#45]
Taking the lead from #34 and [#6631](https://github.com/devtools-html/debugger.html/issues/6631), I went ahead and extended the same design to the rest of the right sidebar panes (watch expression, breakpoints, scopes, XHR breakpoints). Where there was no detail I interpolated from the discussions and used my judgement.

Note that this does not include the Call Stack pane as [there's already a PR working on it](https://github.com/devtools-html/debugger.html/pull/7624).

## Overview
![side-by-side](https://user-images.githubusercontent.com/15959269/50720077-474d2680-1074-11e9-804b-8ce51e8217b5.png)

## Pane Breakdown
<img src="https://user-images.githubusercontent.com/15959269/50720074-297fc180-1074-11e9-952b-6e42fde08482.png">

### General:
- Components should be snapped to a 4px grid vertically and horizontally ([per Photon spec](https://design.firefox.com/photon/visuals/grid.html))
- Pane headers are font-size 12px, code breakpoints (monospace) are 10px, the rest are 11px
- Rows are standardized with 20px height

### Vertical:
- There should be a 4px top and bottom padding for any list or input box <details> <summary>Click here for example</summary> <img src="https://user-images.githubusercontent.com/15959269/50720151-95165e80-1075-11e9-94d0-57294d7715c7.png"> </details>
- Where there’s no list/input box for the pane, a 4px bottom padding should be added to the option element <details> <summary>Click here for example</summary> <img src="https://user-images.githubusercontent.com/15959269/50719794-7f059f80-106f-11e9-9190-d53e5357a536.png"> </details>
- 4px bottom paddings should be inclusive of a 1px border (3px padding + 1px border) <details> <summary>Click here for example</summary> <img src="https://user-images.githubusercontent.com/15959269/50719796-8331bd00-106f-11e9-961c-4fdf0f15bc1a.png"> </details>
- When a 1px border is needed between two elements, they should be added to the first element and not the second element <details> <summary>Click here for example</summary> <img src="https://user-images.githubusercontent.com/15959269/50719797-89279e00-106f-11e9-8351-ad5b42c06ce2.png"> </details>
- Elements with a border should have a height (border included) that is aligned to the 4px grid <details> <summary>Click here for example</summary> <img src="https://user-images.githubusercontent.com/15959269/50719801-917fd900-106f-11e9-92b3-9f5503c3f33f.png"> </details>

### Horizontal: 
- All elements (apart from pane headers) should be indented from the left by 20px <details> <summary>Click here for example</summary> <img src="https://user-images.githubusercontent.com/15959269/50719807-a197b880-106f-11e9-985b-a115dfae5b4e.png"> </details>
- The indented element should include both the text label and any checkbox/arrow <details> <summary>Click here for example</summary> <img src="https://user-images.githubusercontent.com/15959269/50719810-a6f50300-106f-11e9-9636-560517056ba4.png"> </details>
- The text label should start 16px after the start of checkbox/arrow to its left <details> <summary>Click here for example</summary> <img src="https://user-images.githubusercontent.com/15959269/50720164-c55dfd00-1075-11e9-805d-a10620ac2ce8.png"> </details>
- Indented children elements should include its parent's indentation and a new 16px indent <details> <summary>Click here for example</summary> <img src="https://user-images.githubusercontent.com/15959269/50720155-a19ab700-1075-11e9-8960-aaf894271dcf.png"> </details>

### With measurements and vertical separation
<details> <summary>Click here to show picture</summary> <img src="https://user-images.githubusercontent.com/15959269/50720071-1ec52c80-1074-11e9-81f2-fe5f58bc0f32.png"> </details>

### With measurements and vertical separation
<details> <summary>Click here to show picture</summary> <img src="https://user-images.githubusercontent.com/15959269/50720073-297fc180-1074-11e9-96ce-9c9907f157d2.png"> </details>

### Without markup
<details> <summary>Click here to show picture</summary> <img src="https://user-images.githubusercontent.com/15959269/50720074-297fc180-1074-11e9-952b-6e42fde08482.png"> </details>

**Comment by notjaril** [comment]
Opening the issue here since it's UX related - once the ball gets rolling we can move it to debugger.html if that's better.

Thoughts? @darkwing @mcroud @fvsch @violasong

**Comment by darkwing** [comment]
@fvsch @violasong @mcroud Could we fast track evaluation and discussion on this?  Getting hard numbers ASAP would be incredibly helpful as we look at to add Event Listener and DOM Listener panels in Q1

**Comment by mcroud** [comment]
Superb! This looks really really good.
So I'm just going to go through your items here and relay my stream of thought!
I'm happy with the 4px padding for top and bottom of panels being a standard.

Pane header text as 12 and pane body as 11 went down well with the Callstack panel so I'm very happy with that. Could you just elaborate on "code breakpoints are 10px", is this because monospace renders larger anyway?

> Rows are standardized with 20px height

I recall a discussion or proposal about having the option of two accepted row sizes? Not sure if anyone can elaborate on my fuzzy memory. Regardless 20px worked well for Callstack pane so happy here.

> All elements (apart from pane headers) should be indented from the left by 20px 

It might be me interpreting this wrong and that you're including the twisty arrow here, but the pane headers are also 20px from the left, the below image is from the yet to be finalised pane's documentation:

![pane-sizes](https://user-images.githubusercontent.com/42435754/50773461-cd41bb00-1288-11e9-97e8-7b082fea918b.png)

So the pane header starts (going from left to right) with 6px padding, then an 8px twisty arrow, then another 6px padding.

I like standardising the 16px horizontal inset for checkbox and child rows.

For the right edge padding of pane headers I believe the first pane doc draft proposed 20px, so on the below image for example we would have 20px between the "+" and the right edge. Looking at a pane with closable rows with ❎ buttons perhaps 20 is too much, we have 12px proprosed here, what does everyone else think?

<img width="714" alt="screen shot 2019-01-07 at 14 50 56" src="https://user-images.githubusercontent.com/42435754/50774622-cff1df80-128b-11e9-9511-c49b106b77f7.png">


The 'twisty' arrow should be the new one below:
[Pane-arrow.svg.zip](https://github.com/devtools-html/ux/files/2733036/Pane-arrow.svg.zip)
An 8 x 8 pixel icon containing an 8 x 5 pixel SVG.

Aside from a little clarification there's little I could say I have an issue with here, cheers and good job!

**Comment by notjaril** [comment]
> Pane header text as 12 and pane body as 11 went down well with the Callstack panel so I'm very happy with that. Could you just elaborate on "code breakpoints are 10px", is this because monospace renders larger anyway?

Exactly - the monospace font used for code (Menlo) rendered larger, where Menlo 10px is equivalent to the default font (San Francisco) 11px. 

>I recall a discussion or proposal about having the option of two accepted row sizes? Not sure if anyone can elaborate on my fuzzy memory. Regardless 20px worked well for Callstack pane so happy here.

The one I've found was in [#6631](https://github.com/devtools-html/debugger.html/issues/6631), where 24px was as an option if taller rows were wanted. It was also discussed in [#34](https://github.com/devtools-html/ux/issues/34), though I agree with the line of thought that for dev tools, compact information is preferable.

>It might be me interpreting this wrong and that you're including the twisty arrow here, but the pane headers are also 20px from the left, the below image is from the yet to be finalised pane's documentation:

I just meant that any non-header rows should be indented 20px from the left. As for pane headers, I like your mockup and agree the pane header text should be 20px from the left. Although with my current measurements I think it's actually 19px from the left (4px padding+15px arrow)

![screenshot](https://user-images.githubusercontent.com/15959269/50778308-a1640c80-126b-11e9-81a7-ed18ba61e701.png)

**Comment by fvsch** [comment]
> Superb! This looks really really good.

Agreed.

For the expand arrow (well, triangle), you can find it here too:
https://searchfox.org/mozilla-central/source/devtools/client/themes/images/arrow.svg

> I recall a discussion or proposal about having the option of two accepted row sizes?

We mentioned that both 20px and 24px could work, and we needed to try them out.
I’m pretty happy with how 20px renders here. With the added 4px top/bottom padding for each row group, it doesn't look cramped. I’d say 20px is a keeper for this sidebar.

**Comment by fvsch** [comment]
For typography, it would be great if we could use the main existing font-family/size combinations, rather than adding new ones. That would be:

1. Headers and tabs: sans-serif at 12px (line-height often unspecified, but 16px is good here)
2. Other non-code text labels: sans-serif at 11px (line-height often unspecified, but 14px is good here)
3. Code: monospace at 11px (line-height often at 'auto', resulting in 13 or 13.5px; 14px in the Console; planning to move to 15px for the Inspector, Console and most source code views)

It would be nice to also decide on what content should be sans-serif and what content should be monospace. It seems that the Debugger's sidebar is mostly sans-serif, even for JavaScript object representations and values, with one exceptions: code breakpoints. That feels strange. Maybe we should use sans-serif for everything there (_alterntively_, use monospace for more things). It might be that we only have monospace for code breakpoints because of the syntax coloring implementation, which we could override.

I'll also argue that JavaScript object representations (e.g. the expanded `arr(10)` in Watch Expressions and `window` in Scopes) should be more compact, and use a tighter line-height (probably 14px, maybe 15px). That would be more consistent with how we use object representations in other tools (Console, Network details).

**Comment by darkwing** [comment]
Let's keep fonts as is for now -- it's an unrelated, simple change

**Comment by fvsch** [comment]
> Do we think this is the best course of action given the possibility of different checkbox sizes?

We should check the checkbox size on Windows (Windows 10 only maybe). If it's in the 12-14px range, we should be good. I'm okay with having a potential 1-2px imprecision range here, between Windows and macOS. On Linux, the checkboxes may be bigger, but I suggest that we don't optimize for that.

> I think the only remaining discussion point is whether there is a sort of fixed baseline of 20px for rows which may include a 1px border, or whether rows are 20px and may have a 1px border between them (not apart of the 20px row height).

Strongly in favor of rows being 20px _excluding borders (if any)_.
This is how we manage toolbars, for instance. (When we don't, in a couple places, it's a known bug with work-in-progress patches.)

On a 20px grid, if you have a 14px object that is vertically centered, you can have 3 pixels of padding on the top and the bottom. If you eat one pixel of the bottom padding to draw a border, you get a misaligned object: 3px whitespace on top and 2px whitespace on bottom. This 3/2 difference is humanly visible and feels off, IMO. (On a bigger scale it can be less of an issue.)

Content rows should not be implemented with `height: 20px`, because that does not respond well to text that wraps on 2 or more lines, font-size changes, etc. The CSS implementation should probably look more like this:

```
.some-content-row {
  padding: 3px 8px;
  padding-inline-start: 20px;
  font-size: 11px;
  line-height: 1.2727; /* 14px */
}
```

Then you get a 20px row for one line of text, 34px for two lines, and so on. If you add a border, the element itself will be 21px tall, but its content will be (and look) 20px.

**Comment by notjaril** [comment]
>On a 20px grid, if you have a 14px object that is vertically centered, you can have 3 pixels of padding on the top and the bottom. If you eat one pixel of the bottom padding to draw a border, you get a misaligned object: 3px whitespace on top and 2px whitespace on bottom. This 3/2 difference is humanly visible and feels off, IMO. (On a bigger scale it can be less of an issue.)

>Then you get a 20px row for one line of text, 34px for two lines, and so on. If you add a border, the element itself will be 21px tall, but its content will be (and look) 20px.

This makes sense, though it's not a problem with the right sidebar since none of the content rows wrap their text. I do see how flexibility with font-size/line-height and symmetrical visual spacing is handy across devtools, so not being restricted to the 4px multiple for sizing is a good thing.

>I think the only remaining discussion point is whether there is a sort of fixed baseline of 20px for rows which may include a 1px border, or whether rows are 20px and may have a 1px border between them (not apart of the 20px row height). Does that sound right?

I think so, and having 1px border between them sounds good!

**Comment by notjaril** [comment]
Last remaining point is:

>I'll also argue that JavaScript object representations (e.g. the expanded arr(10) in Watch Expressions and window in Scopes) should be more compact, and use a tighter line-height (probably 14px, maybe 15px

I'm biased towards having more spacing and having it be 20px high, since eye strain while inspecting object representations is one of my least favorite things. Although I also see the case for keeping it the way it is (15px) so that you can fit more lines in the same space, and hopefully find what you're looking for quicker. 

@darkwing thoughts on 20px vs 15px for JS object reps?

Once we tie this part up, I can come up with a final spec (changing this and the border) and move it to debugger.html to start implementing. If I'm missing anything else let me know!

**Comment by mcroud** [comment]
Great, I think we will settle with 1px borders being seperate from rows then 👍 

A quick and dirty visual comparison:

![object-row-height](https://user-images.githubusercontent.com/42435754/51310893-8cdbfd00-1a3f-11e9-8f9a-393f335a8eef.png)

**Comment by darkwing** [comment]
I defer to @mcroud on the 15px vs. 20px thing. :)

**Comment by fvsch** [comment]
I vote 15px for consistency with how we display those objects in the Console.
(Currently with a 14px line-height, moving to 15px in the near future.)

**Comment by mcroud** [comment]
I'm 100% for making things easier to scan for users, but I'm also not aware of any reported issues with the current 15px implementation which would make the argument to change it a lot easier (I'm not the best searcher in Bugzilla but wasn't able to find anything - not that it NEEDS to be reported to be an issue mind.)

We do provide the means to allow users to zoom in and increase the text size so I feel in this instance, given that this is also how it has looked in the console object inspector panel, I would vote to remain at 15px - at least for now.

**Comment by fvsch** [comment]
I'm not sure what you are representing with the dotted borders.

If you wanted to add dotted borders in the rendered UI, I think this makes things a bit too visually busy.
If it's just a representation of spacing (representation which should not be rendered UI), they're mostly okay, except we're probably not going to leave 1px blanks between rows when we don't have a visible border, so those 1px spaces are probably not necessary. (We can move to implementation with this caveat.)

Otherwise things look great. My only nitpick would be that the "Pause on exceptions" section could use a 2px or 4px vertical padding (making its total height 24 or 28px), right now it looks a bit cramped.

**Comment by jaril** [comment]
The dotted borders are just a design guideline for visually identifying separate vertical rows to make it easier to match pixel values to what it is they're measuring. The measured values are still correct for implementation, as the dots just signifies the bottom inner border of the previous row.

For example, an element with 10px height is visualized in the mockup as a 9px of content + 1px of border on bottom. Ignoring the 1px border on the bottom still gives you the 10px as identified in the measurements.

On second thought I should have taken them out of the side-by-side preview. Here it is without the dots:
<details>
<summary>[IMG] Side by side without dotted lines</summary>
<image src="https://user-images.githubusercontent.com/15959269/51607439-a15a4280-1ee2-11e9-94f1-0000219c7df0.png"></image>
</details>
<br/>

Agree on `Pause on Exceptions`/`Pause on any URL` being too cramped. Here are mockups for 2px/4px. I'm leaning towards 4px for consistency - let me know what you think.

![options-vertical-padding-01232019](https://user-images.githubusercontent.com/15959269/51609197-78887c00-1ee7-11e9-8724-b71730115cb4.png)

**Comment by fvsch** [comment]
> Agree on Pause on Exceptions/Pause on any URL being too cramped. Here are mockups for 2px/4px. I'm leaning towards 4px for consistency - let me know what you think.

The consistent 4px is great, let's go with that.

Thanks again for all your work, and the level of detail of the blue/red lines. :heart:

**Comment by jaril** [comment]
Final spec (with the new 4px padding around options checkboxes)

## Preview
![side-by-side-01242019](https://user-images.githubusercontent.com/15959269/51646282-efecf880-1f45-11e9-9992-25295d59f3e8.png)

## Overview of new panes
![options-vertical-padding-01242019](https://user-images.githubusercontent.com/15959269/51646287-f54a4300-1f45-11e9-888e-c27028b9efd2.png)

**Comment by violasong** [comment]
Outstanding work! Thanks so much @jaril. I can't wait to see this implemented!

**Comment by violasong** [comment]
And of course, big thanks to Florens and Matt for y'all's work on this too :)

**Comment by mcroud** [comment]
Wonderful! what a collaborative result 🎉 
Final spec looks great! Thanks @jaril and @fvsch 👏

**Comment by digitarald** [comment]
@violasong would it make sense to add those results to the devtools photon docs?

**Comment by violasong** [comment]
@digitarald Yes, good point - will add to backlog.

**Comment by violasong** [comment]
(I think this issue can be closed - let me know if otherwise.)

**Comment by fvsch** [comment]
Yep, good to close.

There are some good mockups in this issue that we could reuse -- or get inspiration from -- of we want to document some patterns, but that's true of a few already closed issues. If we get around to making more generic design docs, we can revisit the closed issues to retrieve some material.

**Comment by violasong** [comment]
That sounds good to me - thanks Florens!
