### ISSUE TITLE
[Profiler] Profile upload dialog with customizable PII removal

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#54]
UX for https://github.com/firefox-devtools/profiler/issues/1802
Team: @canaltinova, @gregtatum, @fqueze and @digitarald.

**Background:** The profiler needs to keep users from accidentally sharing data that they are not aware of but provide user choice to include more data.

Guiding principles (from the [PRD](https://docs.google.com/document/d/1Uc07GYeWLrfOJhWIYm6bZuBnhA85_ULhprpLkUkr7nk/edit#heading=h.cd03h8rtx2b5)):
- Share everything by default for Nightly/Custom builds (with a warning for the unaware)
- Share no PII by default everywhere else
- Keep it understandable for technical users

### Designs

**Diverging stage** to find the right interface for users opting into sharing more data and understanding their choices). When _converging_, we can tweak the copy for labels, descriptions and warnings.

Greg created a prototype, in which users uncheck options to include more data: [Deploy preview](https://deploy-preview-1509--perf-html.netlify.com/public/404ff08ee5f412f355264601f12e5feff0ebaee6/calltree/?globalTrackOrder=6-0-1-2-3-4-5&hiddenGlobalTracks=1-2-3-4&localTrackOrderByPid=15249-1-0~15254-0~&range=8.4053_16.7712&thread=6&v=3)

Harald's mockups are exploring the direction of checking boxes to share more data:

![image](https://user-images.githubusercontent.com/8599/54241476-486c5b00-44de-11e9-8a71-c7c44574dd9a.png)

cc @violasong @fvsch for input.

**Comment by fqueze** [comment]
Thanks for starting this discussion Harald!

Random thoughts when looking at the provided mockups:
- Checking boxes to have more data included seems more natural to me than unchecking things.
- I like the idea of including information about how much data will be included like on the mockup at the top right (ie. '4 hidden threads', '3.1s outside the time range', the names of the add-ons, the hostnames, ...). I think if we decide to do it, it doesn't have to block the rest of the design and we can keep it for a follow-up.
- I like the idea of showing the size of what will be uploaded, but for me this doesn't have anything to do with sanitization (the size of the file doesn't relate to the amount of PII shared), so rather than showing this information at the top of the list of checkboxes, I would prefer showing it close to the Publish button. If we replace the current cryptic error message we have when the upload fails because the file is too big with a message that says that; having the info about the size of the upload will nicely make the error actionable!
- Having the checkboxes in 2 columns (bottom left mockup) is harder to process for me.
- The (i) icon in the bottom right mockup looks nice.
- I dislike the "Download" button in the bottom right mockup. The word "download" would make me worry that my data is already online somewhere. And even if we word it differently (eg. "Save"), I don't see the point of sanitizing PII out of a profile that's going to be saved locally. I mean, I could make up some unusual use case where that would be nice, but I can't think of any that deserves such a prominent position in the UI.

**Comment by digitarald** [comment]
> I like the idea of showing the size of what will be uploaded, but for me this doesn't have anything to do with sanitization

Agreed, it probably should be a combination of both showing what kind of data gets removed per category and making it less prominent. The choices are not about reducing the size, but stripping private data. I did like how the data removal summary can be a header for the section, but a more privacy focussed stat would make more sense.

> The (i) icon in the bottom right mockup looks nice.

This section could be informational and wrapped in a photon's relevant [helper](https://design.firefox.com/photon/patterns/helpers.html) style. Those don't seem to have icons though, but can either have a _Learn More_ link or tooltip (_Relevant_).

> I dislike the "Download" button in the bottom right mockup.

Good one; sounds indeed like it's already in the cloud. Probably just needs some better copy; like _Save_. This might clash with renaming the label in the top-level button to "Publish"; but maybe it is not that important as secondary option.

**Comment by digitarald** [comment]
@violasong to help with your backlog prioritization, we are aiming to land this work before the end of Q2 and the backend work is nearly completed; so only frontend remains.

**Comment by violasong** [comment]
Sounds good! I like where the mockups/comments are going, and will respond in more detail soon.

**Comment by digitarald** [comment]
@violasong we have a profiler planning meeting tomorrow and I'll be PTO for 2 weeks after that – would it be feasible to have some initial input by EOD today? Happy to jump on a chat to provide more context if needed.

**Comment by digitarald** [comment]
Other thoughts that might be considered in the UI, adding to the notes before:

- Give users more context when needed to understand some of the technical and complex options that don't relate to "tangible data" (hidden threads, time ranges, etc)
- It might make sense to hide the complex options field for release users (vs pre-release dev audience), similar to what @gregtatum implemented, so users are not overwhelmed with making decisions for 6+ checkboxes. A spin on Greg's UI would be showing a checkbox ala _"Opt-in to include additional data …"_, which then unfolds the additional options.

**Comment by violasong** [comment]
Yes! Will look at it this morning

**Comment by violasong** [comment]
Here's what I would suggest based on the above points:

--
**Share Performance Profile**

Upload your profile and make it accessible to anyone with the link. By default, your personal data is removed.

v Include additional data that may be identifiable
- [ ] Hidden tracks
- [ ] Hidden time range
- [ ] Screenshots
- [ ] Resource URLs

[Cancel] [Save] [Publish]

--

- I think having a short title helps with cognitive load. Calling it "Share Performance Profile" ties it in with the button wording.
- Shorter intro paragraph and secondary title
- 'Positive' checkbox options so fewer double-negative issues
- Info icon looks good too!

**Comment by digitarald** [comment]
> v Include additional data that may be identifiable

Would you recommend to hide that section by default or just receive a "section" styling?

**Comment by violasong** [comment]
Ah, not sure - do you foresee these options used like 5% of the time or
30%+? Is it important to list out all the options for discoverability in
case the dev is missing something? It’s not too much info if we just have
4-5 checkboxes, so maybe I’d err on default-visible.

**Comment by julienw** [comment]
Hey, I filed an issue in https://github.com/firefox-devtools/profiler/issues/1957 after this was implemented because I found the way checkboxes work confusing. Especially sometimes `checked` means `filter out` and in other locations it means `include`.

**Comment by digitarald** [comment]
> It’s not too much info if we just have 4-5 checkboxes, so maybe I’d err on default-visible.

Seems like that is the way forward until we get more checkboxes. Related https://github.com/firefox-devtools/profiler/issues/1957#issuecomment-484491272 had a great idea on how to conceptualize the removal of hidden information and private data.

> Here's what I would suggest based on the above points:

@violasong how would this be worded for Nightly, where we want to share everything by default. Just pre-opening the section and having the checkboxes checked might be enough.

**Comment by digitarald** [comment]
v0 landed, closing for now.
