### ISSUE TITLE
Show console error count in toolbox

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#58]
Console errors are a guiding beacon for web developers, during development and in production (collected via error reporting services). Making them visible in top-level UI can hint important.

Work started in [bug 1109362](https://bugzilla.mozilla.org/show_bug.cgi?id=1109362).

cc @nchevobbe @janodvarko @fvsch @violasong 

## Background

We have a lot of prior art, so we should pick the best fit and improve based on that.

Considerations:

- Should consider the transition from no errors to 1 error; minimizing visual jitter
- Should support lazy loading (having a placeholder or empty spot), to allow prioritized loading of the current panel.
- Should consider that increments don't cause extraneous layout and jitter, by changing the size of the element
- MVP might just include errors, not warnings

## Prior Art

Observations & _Opinions_.

### Chrome

![image](https://user-images.githubusercontent.com/8599/56325488-3c9c3600-6127-11e9-8791-1ee3803eb54f.png)

- In the right-aligned section of the toolbox. _Probably what users are used to that are trained on Chrome_
- Click opens/focuses Split Console (if Console isn't the active panel). _This is nice as it gets more users into the split console that might otherwise not be aware and doesn't interrupt the current tool to show console errors._ 
- More errors showing causes the space for the tabs to shrink (and more tabs to be hidden)

### Firefox's GCLI

<img width="115" alt="image" src="https://user-images.githubusercontent.com/8599/56325529-710ff200-6127-11e9-8923-5485cbc4623d.png">

### Safari

<img width="571" alt="image" src="https://user-images.githubusercontent.com/8599/56325635-c0562280-6127-11e9-9170-bdf7c8ffb01d.png">

- In the "command center" with other page/status details.
- Shows logs, warnings and errors. _Not sure why it would be ordered that way. I also missed that logs is shown, as it is pretty low contrast compared to the warning and error icon._

### Edge

<img width="378" alt="image" src="https://user-images.githubusercontent.com/8599/56325778-64d86480-6128-11e9-8f83-1df3e8f96e37.png">

- Just error count, with an error icon.

### Firebug

<img width="115" alt="image" src="https://user-images.githubusercontent.com/8599/56326025-49ba2480-6129-11e9-8918-809144a4c718.png">

- Uses status bar, which doesn't exist anymore.

**Comment by digitarald** [comment]
Victoria's mockups from the discussion in [bug 1109362](https://bugzilla.mozilla.org/show_bug.cgi?id=1109362). 

Iteration 1:

![image](https://user-images.githubusercontent.com/8599/56326375-a4a04b80-612a-11e9-8ee5-dd85fc4eb282.png)

> I'd suggest making it more compact by just showing the number with red coloring. I gave the solid red badge a try but it looked way too intense. What about just red text/slightly smaller font/some text separator like a colon?

Iteration 2:

![image](https://user-images.githubusercontent.com/8599/56326348-863a5000-612a-11e9-8d4c-6b79154f3cb8.png)

> Brighter red may look nicer, and not need a separator

**Comment by digitarald** [comment]
I prefer the Chrome placement

- It separates the errors from the tab and uses the split console as click action which is the least intrusive (vs switching tabs to check console logs). If users want to see more, they can always click on the Console to dig in further.
- The other upside is that tabs usually have some space to the right, so the warnings appearing and growing in size in that space does not cause layout jitter in many cases.

**Comment by janodvarko** [comment]
Yes, I like the placement of the number on the right side. 

It would be also great to have an (error) icon next to the number, so it's clear what the number represents. Or perhaps we could experiment with the solid red badge again (with the number inside)? Having it far right doesn't have to feel too intense (as when it's between tabs). 

Honza

**Comment by fvsch** [comment]
### Error count in Console tab

I like the simple red count (Iteration 2). Here's a test with a solid red badge look (done in CSS on Linux, exact rendering depends on font and resolution):

![Screen Shot](https://user-images.githubusercontent.com/243601/56347152-0234a680-61c4-11e9-9146-9a67a94d4a1b.png)

Looks alright-ish, maybe a bit too strong indeed.

> Should consider the transition from no errors to 1 error; minimizing visual jitter

In that scenario, I wouldn't reserve a ~20px blank space in the Console tab in the "no error" state, it looks rather strange. So we would have to live with a jump between the "no error" and the "some error(s)" state. But we can avoid jumps between different error counts (between 1 and Infinity).

### Error count on right side of toolbar

- Not a fan of opening the split console on click, mostly because I'm not a fan of using the split console along tools like the Inspector (which is already very visually busy!) and only use it with the Debugger.
- Can we make it more compact when docked to the side? Just an error count and no warning count maybe? No icons?
- Can we make it optional (on by default), like most other elements in the toolbar?

If the error count is disabled, I wonder if we should add some kind of marker in the Console tab. There's the notification marker in Firefox tabs, perhaps a red variant could work?

<img alt="screenshot of firefox tab" width="225" src="https://user-images.githubusercontent.com/243601/56352142-e5ea3700-61ce-11e9-8477-dc5f5ed53aa7.png">

**Comment by digitarald** [comment]
> Here's a test with a solid red badge look (done in CSS on Linux, exact rendering depends on font and resolution):

That also looks good, from a styling perspective (not considering the tab vs right-aligned decision). If we feel we need to tone it down, we can still pick a less vibrant red

> Not a fan of opening the split console on click, mostly because I'm not a fan of using the split console along tools like the Inspector (which is already very visually busy!) and only use it with the Debugger.

The trade off is a hefty context switch from the current tool to a new panel. As example, if a user is the process of editing CSS or stepping, see an error appearing, clicking – they will be ejected out of their flow into a new panel. My hypothesis would be that split console is less jarring. Lastly the consistent UX argument is that Chrome does it and users would be surprised if our interaction diverges – which raises the bar for picking another action.

Maybe follow up can be making the split console logic better on how much space it takes when opening (I noticed it can cause some strange layouts by squishing some parts of 3-panel layouts.

> Can we make it more compact when docked to the side? Just an error count and no warning count maybe? No icons?

Agreed, good thing to try out. Having a red badge with error count works as well as the error-icon + counter, with half the space. We also have prior art with addon icon badge counters

<img width="31" alt="image" src="https://user-images.githubusercontent.com/8599/56396985-6ff9c600-61f6-11e9-8ac5-87c0fc3ad1d3.png">


> Can we make it optional (on by default), like most other elements in the toolbar?

Given that all browsers show their indicator by default, I would also propose that. Having a preference to disable the element makes sense though.

**Comment by violasong** [comment]
The badge with darker red still seems pretty intense/alarming to me. If we're ok adding a small icon, in outline mode, it looks pretty good I think. I was assuming we won't be adding an indicator for console warnings, only error. 

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/55994/56517807-bc911a00-64f2-11e9-8a6c-7550d3f4959a.png">

Not sure about the split console question.

**Comment by digitarald** [comment]
> If we're ok adding a small icon, in outline mode, it looks pretty good I think.

How would it look filled? Would the text in red might be easier to read in black? Then it basically looks like Chrome I guess, just with our icon 😅 

> I was assuming we won't be adding an indicator for console warnings, only error.

Yes, for now. Could we try out how it looks for brainstorming?

**Comment by violasong** [comment]
Oh argh, it's looking brighter in my screenshots than in my sketch for some reason. I meant for it to look more like this:
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/55994/56696303-49c5a180-66a0-11e9-9a97-ace3ef45dae5.png">

Here's how chrome style looks.

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/55994/56696699-70380c80-66a1-11e9-9348-7026de9854e6.png">

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/55994/56696500-db351380-66a0-11e9-8e9b-c8e149fd454f.png">

**Comment by digitarald** [comment]
@violasong what's your preference? I am fine with either but prefer the second one as it provides better contrast and we don't have other devtools interfaces with red text and outlined icons.

Final thoughts, @janodvarko @nchevobbe ?

**Comment by violasong** [comment]
The first one plays off the (?) icons, but I can see what you mean about the red outline being weird. 

I worked on the second one some more - shrinked the icon and number so it's a little less prominent. I'm liking this a lot more now and am happy to go with it.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/55994/56935156-28035a80-6aa4-11e9-87ef-f2e76f7fdd91.png">

**Comment by violasong** [comment]
Attached the icon — it's a smaller version of the photon one, 10x10, with slightly larger exclamation mark. Should be filled with red 60.
[error-small-compressed.svg.zip](https://github.com/firefox-devtools/ux/files/3129608/error-small-compressed.svg.zip)

**Comment by janodvarko** [comment]
- I like the last screenshot from @violasong 
- I also prefer having the counter on the right side and opening the split console when clicked.

So, for me this looks great, thanks!

Honza

**Comment by fvsch** [comment]
@violasong Would 12px icons work here or is that too big and 10px is preferable?

12px icons follow the recommended "small" size from Photon and that's what we use in the Console.
If we want a full (Chrome-style) alert icon we already have one for Console errors.

Here it is (bottom center) compared to the 10px icon (bottom right) and Console icons (top row):
<img width="153" alt="Error   Warning@2x" src="https://user-images.githubusercontent.com/243601/57030709-edd1be80-6c45-11e9-832b-54c08e4b0a90.png">
SVG: [Error count icons.zip](https://github.com/firefox-devtools/ux/files/3135301/Error.count.icons.zip)

Side note: it seems you set your 10px icon in a 11px artboard and with the center stroke sitting on half-pixels? Was that on purpose because it rendered better in your tests, or an export artifact maybe?
In my tests that version looks good @2x, but the center shape has blurry edges @1x:
![11px-error-icon-rasterization](https://user-images.githubusercontent.com/243601/57030846-5751cd00-6c46-11e9-86de-fc2ecb08636b.png)

In the attached SVG I've realigned it to a 10px canvas, but maybe that's not particularly better.

**Comment by hemakshis** [comment]
Hi, What about the tooltip text that should be displayed when the user hovers over the icon?
Should we add something like "<count> errors" (done by Chrome) or "Open Split Console" or "Show in Split Console"?

**Comment by violasong** [comment]
Ah, the .5 pixels on 11px artboard thing was a mistake! Thanks for fixing it.

For me the 10px level of prominence with larger white text helps reduce the alarm/discomfort of seeing a red error dot. I'm assuming people often want to ignore it if they're working in the Inspector, etc.

@digitarald Why thumbs-down?

**Comment by digitarald** [comment]
> @digitarald Why thumbs-down?

Oh noes, I meant (double, triple) thumbs up! The smaller icon is excellent.

If this is wrapped up, I'd like to close this issue as implementation work has started. We can re-open it in case of follow up questions.

**Comment by violasong** [comment]
Haha Yay! Will close the issue.

**Comment by nchevobbe** [comment]
> > implementation work has started
> 
> Can you link a PR / issue / something where we can see the progress?

Work was happening in https://bugzilla.mozilla.org/show_bug.cgi?id=1109362

**Comment by digitarald** [comment]
If people want to help contribute, [bug 1109362](https://bugzilla.mozilla.org/show_bug.cgi?id=1109362) is a intermedia-first-bug with a first draft of a patch.
