### ISSUE TITLE
[Network] Content search

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#59]
**💡 Stage: Converging**

Why P2: Contributor project and not tied to team deliverables, but potentially includes an existing open UX issue and can make life easier for webcompat debugging.

Implementation: [Bug 1454312](https://bugzilla.mozilla.org/show_bug.cgi?id=1454312).

## Stories
- When looking for resources, I want to search for keywords that appear in either headers or body, so that I can jump to the specific part of the response that has the keyword
- When looking for caching headers, I want to find the resources with specific (case insensitive) headers, so that I can assess their cache setting and behavior.
- When seeing a specific content in a site, I want to find the resources that contains that content/logic (case sensitive), so that I can open it and understand how the content was created.

## Requirements

- UX must show a preview of the match for context
- UX should allow stepping through results for easy scanning
- UX should be somewhat unified with Console's planned search feature #38 and Debugger's file search
  - Difference is that most data in the Console is visible by default (except stacks that might be collapsed), so inline search works fine – whereas resources have to opened in the sidebar to preview which header/body-location matched the search
- UX could consider devtools-wide file search for a long term solution

## Exploration

The options out there seem straightforward:

1. Re-use the Debugger's file search UI
  - Pro: More horizontal space to show results and preview matched context
  - Contra: No easy stepping (at least in current Debugger implementation)
2. Sidebar-based search similar to Chrome's Network search, VSCode's file search
  - Pro: Allows stepping through results. Could integrate as tab with other left-side panels.
  - Contra: Sidepanel has limited horizontal space. Needs extra integration work with existing 3-panel layouts or 2-panel layouts like Network
4. Hybrid?
5. Something else completely?

### Firefox Debugger's File Search

<img width="749" alt="image" src="https://user-images.githubusercontent.com/8599/56436797-f2839380-6291-11e9-8660-6a3bfa1967a2.png">

### VSCode's File Search

<img width="548" alt="image" src="https://user-images.githubusercontent.com/8599/56436811-029b7300-6292-11e9-918e-6b154bf912da.png">

### Atom's File Search

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/8599/56437159-3dea7180-6293-11e9-8bb5-c97ae6882272.png">

### Chrome's Network Search

https://umaar.com/dev-tips/170-network-search/

![image](https://user-images.githubusercontent.com/8599/56436520-f95dd680-6290-11e9-82c5-d074b4adc30c.png)

### Chrome's Console Search 

<img width="590" alt="image" src="https://user-images.githubusercontent.com/8599/56435076-fa403980-628b-11e9-9802-339310d34d04.png">

### Chrome's Search panel 

<img width="583" alt="image" src="https://user-images.githubusercontent.com/8599/56436431-b3a10e00-6290-11e9-98c7-6d3dfa7d086c.png">

**Comment by janodvarko** [comment]
> Sidebar-based search similar to Chrome's Network search, VSCode's file search

I like the idea of having a new Search panel that allows stepping through results - highlights the results in the panel content and/or in the Side panel details (so, the user can see both at the same time).

> Contra: Sidepanel has limited vertical space. 

Did you mean horizontal space? (height of a side panel is the same as height of the main panel, no?).

I also like having the Search panel on the left side, not as part of the right side panels. Again, since the user can see both (search results and highlights) at the same time.

Perhaps Debugger could move the search panel to the left (as part of Sources/Oultline tabs) at some point? (so, we are consistent)

> Hybrid?
> Something else completely?

If the Search panel opens at the bottom like the Split Console, it can be nicely reused by all panels (just like the Split Console).

Honza

**Comment by digitarald** [comment]
> Did you mean horizontal space? (height of a side panel is the same as height of the main panel, no?).

Yes, thank you. Fixed.

> Perhaps Debugger could move the search panel to the left (as part of Sources/Oultline tabs) at some point? (so, we are consistent)

@jasonLaster was that considered during the search panel design or later?

> If the Search panel opens at the bottom like the Split Console, it can be nicely reused by all panels (just like the Split Console).

Would it work like Chrome's Search panel or different?

**Comment by janodvarko** [comment]
> Would it work like Chrome's Search panel or different?

Content of the Search panel would be the same as in Chrome (or as the current search results in Debugger). The main benefit would be the layout - having independent search panel that doesn't overlap the current panel where the user is searching.

Chrome seems to be a bit inconsistent in what Search panel is used. When searching in the Net panel - there is left-side panel, when searching in Sources - there is bottom panel. Perhaps we could improve that.

We could have only the bottom panel, or use it if already opened, etc.

Honza

**Comment by digitarald** [comment]
@jasonLaster @darkwing @loganfsmyth thoughts on debugger search in side-panel - what are trade-offs that we should consider?

@violasong you had past mockups around search; are there relevant materials and considerations to share here?

**Comment by digitarald** [comment]
Summarizing to move forward: Given the options, we have general agreememt that side-panel search interface checks most requirements and can improve the search experience in Debugger.

I suggest to further converge on that option and start mocking up search panel for Network and, as stretch work, for Debugger (though keeping this issue focused on Network). Happy to take a shot at it, with help from @violasong but other contributions are greatly appreciated.

**Comment by violasong** [comment]
My related idea is the [unified command palette](https://github.com/firefox-devtools/debugger/issues/6260) that works as a global search.

If we ignore fancy search UIs for now, and just think about how the results should look in the current design: I’m still most in favor of my comment from 5 months ago in the [Console bug](https://github.com/firefox-devtools/ux/issues/38#issuecomment-446810063) 🙂 - unified search/filter results. The only rows shown would have a match either in their main info or hidden info, and hidden info matches would show a one-line preview with the search term highlighted. The two different types of results would look different enough so that the user can visually skip to the desired type of result quickly. Main info matches should look more prominent.

My assumption is that the user wants to quickly input something without having to think about whether they want a search or a filter.

Is the extra panel idea easier to implement? UX-wise, it seems unwieldy to me, because it’s more sections between which the eye has to jump back and forth. Maybe it makes more sense for Debugger, as a secondary UI. But with a Console and Network it seems like a main UI to me, so it should take up the main body area.

**Comment by digitarald** [comment]
@violasong 

> My related idea is the unified command palette that works as a global search.

Related, the cmd-p palette definitely comes up a lot in feedback as users have trained that muscle, but the in-file search would probably not be the first problem that it solves for (vs devtools commands, go to file, etc).

> unified search/filter results. The only rows shown would have a match either in their main info or hidden info, and hidden info matches would show a one-line preview with the search term highlighted. The two different types of results would look different enough so that the user can visually skip to the desired type of result quickly. Main info matches should look more prominent.

This sounds like a pretty full-fledged project. Is this based on existing UI from other editors or breaking new ground? I'd be happy to have some UX exploration to better understand this approach and evaluate it better against the other options.

> Is the extra panel idea easier to implement?

The main consideration for the side panel was that the search stays visible while navigating the results. With the modal behavior of the command palette would require a way to get back to the search via magic shortcut (similar to what Debugger has right now, and what users already found cumbersome).

**Comment by violasong** [comment]
> Related, the cmd-p palette definitely comes up a lot in feedback as users have trained that muscle, but the in-file search would probably not be the first problem that it solves for (vs devtools commands, go to file, etc).

Agreed, that's definitely the more experimental part of that idea. Chrome parity could be a good start.

>This sounds like a pretty full-fledged project. Is this based on existing UI from other editors or breaking new ground? I'd be happy to have some UX exploration to better understand this approach and evaluate it better against the other options.

I'm thinking of how a full-text web search will combine results that match either the title or the content. Here's a rough idea of how it could work: 

First one is header match, second one is filename match.
<img width="878" alt="image" src="https://user-images.githubusercontent.com/55994/58669074-df7fcc80-82ef-11e9-9982-edd6bdd3901e.png">

**Comment by digitarald** [comment]
> Agreed, that's definitely the more experimental part of that idea. Chrome parity could be a good start.

As we have interns starting, is is probably a good start for converging towards the sidepanel option.

> I'm thinking of how a full-text web search will combine results that match either the title or the content. Here's a rough idea of how it could work:

This would work in Network panel. Is this goal still to apply the same theme across more panels, mainly Debugger? Lets start a new issue for that though, so we can effectively diverge.

**Comment by violasong** [comment]
>>I'm thinking of how a full-text web search will combine results that match either the title or the content. Here's a rough idea of how it could work:
>
>This would work in Network panel. Is this goal still to apply the same theme across more panels, mainly Debugger? Lets start a new issue for that though, so we can effectively diverge.

I actually don't think the search UIs in Network and Debugger should be the same. 

In Network, searching inside the requests seems so similar to filtering request name that I think the results should be kept together in one list if possible. Adding a search sidebar on the left would give us semi-redundant left and middle columns, and require the user to visually jump across a big, currently-useless middle column in order to switch between the actually-relevant left and right columns. (I know Chrome does it this way, so maybe I'm missing something. I'm working off of designer instinct here rather than personal experience with the Network panel.)

As for Debugger, maybe a sidebar does make sense there if we need a quick way to navigate Find in Project results. However, I don't think it needs any changes to be made in conjunction with the Network changes. I do have this [mockup](https://mozilla.invisionapp.com/share/39IG53NDEW7#/292476298_debugger_Find_In_File) which includes the new tab per search idea that @darkwing mentioned above, and I still like the ideas in there :)

**Comment by violasong** [comment]
Oh, maybe there was a little miscommunication here:

>>>Related, the cmd-p palette definitely comes up a lot in feedback as users have trained that muscle, but the in-file search would probably not be the first problem that it solves for (vs devtools commands, go to file, etc).

>>Agreed, that's definitely the more experimental part of that idea. Chrome parity could be a good start.

>As we have interns starting, is is probably a good start for converging towards the sidepanel option.

I meant Chrome parity only for the command palette.

I'm against Chrome parity for the search sidebar :)

**Comment by violasong** [comment]
Another thing: Would it be correct to say that 1. users usually only want a URL filter, and 2. if we perform a full-text search by default for these users, it could yield too much irrelevant data? (or have perf issues, etc?)

If so: one extra piece of UI that may be necessary for my Network search proposal is some kind of switch to turn on full-text matching. Cmd-F could both activate the field and switch it to a content search.
<img width="419" alt="image" src="https://user-images.githubusercontent.com/55994/58843630-322af280-8628-11e9-800a-99574da33785.png">

However, if we could do the true hybrid approach of just always doing a full-text search, with good visual separation of result type, that would be the cleanest, and reduce the need for the user to make a UI decision before typing in a term.

Example: 
1. First show the matching URLs that also have matching content
2. Then show matching URLs
3. Then show non-matching URLs with matching content
4. Maybe with extra visual indication to separate (1 and 2) and (3)

<img width="505" alt="image" src="https://user-images.githubusercontent.com/55994/58844204-08bf9600-862b-11e9-866d-73a604067252.png">

**Comment by nt1m** [comment]
Note that the current filter input supports text flags, so you can type things like `hello status-code:200` which would basically match all requests with an URL of`hello` and a status code of 200. It also supports negative filtering like `hello -status-code:200`. These are ported from Chrome DevTools.

Just mentioning it since it might be tricky to fit the flags in the content search UX in case of a combined searchbox :)

See: https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list#Filtering_by_properties

**Comment by violasong** [comment]
I've been hoping for a more advanced search bar that can match any of these flag types, e.g. shows requests with 200 status codes if the user just types `200` into the input. Organizing the match types in the results (e.g. similarly to how I describe it in my last comment) would help with any potential chaos, e.g. if there are a lot of URLs that match 200.

**Comment by janodvarko** [comment]
First prototype of Network panel search available.

* [Try build](https://treeherder.mozilla.org/#/jobs?repo=try&revision=5a2fbae276b66be7c0cfaf6ca7dde0a35861dcc4) (Mac, Linux, Win)
* The Search panel can be opened through request list context menu item: `Search ...`
* Meta bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1559343


![image](https://user-images.githubusercontent.com/37785/62703127-c4fd5a00-b9e8-11e9-88af-3f5d7ac5fa2a.png)

**Comment by digitarald** [comment]
@violasong just for some background: We went with the sidebar as it allows @lloan to provide a working solution in its own space and use prior art to build upon. Lets focus this issue on polishing the UI for this.

Long term, we can iterate into bringing both filter actions back together, maybe with your UI idea of exposing additional rows.

Rwlated, the new side panel could also be used for [request blocking](https://bugzilla.mozilla.org/show_bug.cgi?id=1540211), worked on by @darkwing, for which I wanted to start planning the coming days.

**Comment by violasong** [comment]
Ah, that makes sense. Is this slated for 70? I can look at this next week.

**Comment by digitarald** [comment]
Next step is landing it in Nightly and pref it on by default, but we probably want to let bake in Nightly for a bit longer to polish.

**Comment by digitarald** [comment]
MVP landed, follow up bugs will handle any polish.
