### ISSUE TITLE
Polish blocked resource styling

### ISSUE THREAD

**Issue by digitarald** [firefox-devtools/ux#81]
`blocked` throws off the status icon grid, where all other boxes are the same size. Icons might be one idea to solve this, but I'd love to hear more thoughts:

[Mockup](https://www.figma.com/file/j6Uli7YDzIbN1oGhBYCqx7/Blocked-Resource?node-id=0%3A1):

<img width="456" alt="image" src="https://user-images.githubusercontent.com/8599/61485907-1c168e80-a957-11e9-8188-773ed507bb99.png">

Related:
- Landed in [bug 1157817](https://bugzilla.mozilla.org/show_bug.cgi?id=1157817)
- [CSP test page](https://firefox-devtools-csp.glitch.me/)

cc @darkwing @janodvarko

**Comment by violasong** [comment]
Yes, I like the icon idea — for extra clarity we could out the text "(blocked)" after the filename or somewhere where it makes sense. 

I thought at some point we were going to use the content blocking icon for this? 

<img width="68" alt="image" src="https://user-images.githubusercontent.com/55994/61496505-352c3900-a971-11e9-823b-2706f2ac0027.png">

**Comment by digitarald** [comment]
> Yes, I like the icon idea

Great. Do you any preference on which icon specifically or nits on my mockup?

> I thought at some point we were going to use the content blocking icon for this?

This is not about TP specifically. Blocked reasons can be manifold, tracking protection is just one of many: CORS, CSP, Tracking Protection, mixed content, extensions, etc. 

Long form looks like 

![image](https://user-images.githubusercontent.com/8599/61497671-22b3fe80-a975-11e9-8842-0b1d019eb9ae.png)

The `CSP` mention should probably be more sth like `Blocked: CSP`

**Comment by fvsch** [comment]
Re. @digitarald's mockup, if we follow https://design.firefox.com/photon/patterns/errors.html#style the text color should be Red 60, which is a bit lighter/redder.

An icon sounds alright. But I wouldn't use a `X` or "cross" icon because we already use those for actions:
- Close (devtools, RDM, split console)
- Clear input value

For errors, we have precedent in Console and Accessibility, where we use those icons: [error.svg](https://searchfox.org/mozilla-central/source/devtools/client/themes/images/error.svg), [error-small.svg](https://searchfox.org/mozilla-central/source/devtools/client/themes/images/error-small.svg).

Another option is to look at international road signs for "stop" or "forbidden":
- Forbidden: red circle with diagonal line, overlaid on top of another symbol
- Stop: more variation between countries: disc or octagonal background, and content can be an horizontal bar or the word "STOP"

A few tests as 16px icons ([Figma source](https://www.figma.com/file/G1KeEdbrqtGrDqtZHttJ1m/Blocked-Resource-Icon?node-id=0%3A1)):

<img width="96" alt="Blocked resource icon" src="https://user-images.githubusercontent.com/243601/61549358-18b2fe00-aa50-11e9-8b29-cdcafba2497a.png">

(We can use or make 12px icons too if we need something smaller. For reference, the status code badges are 14px tall, so I think a 16px icon would work in that context.)

**Comment by digitarald** [comment]
> Re. @digitarald's mockup

To clarify, the text color is not mocked up but what we have shipping. I only mocked up the icons in the second shot.

> Forbidden

Chrome uses _forbidden_ for Clear across several panels, which is why I avoided it.

<img width="86" alt="image" src="https://user-images.githubusercontent.com/8599/61552456-bf75ab00-aa0c-11e9-8a17-d48535a8ad7c.png">

I like the exclamation mark combined with red, generic enough and the right level of severity thanks to the color.

@fvsch would you use just icons or icon + red badge as I mocked it up? Might be call based on visual rythm; but other status entries also don't have a visible badge pill (cache HTTP response codes) so diverging from it would be an easy option.

**Comment by fvsch** [comment]
> Chrome uses forbidden for Clear across several panels, which is why I avoided it.

I thought about that, but since it's kind of a semantic mistake on their part (I've witnessed coworkers struggling to understand this icon in Chrome), I don't think we should rule it out.

> would you use just icons or icon + red badge as I mocked it up

My gut feeling was just the icon. We can try both and see what works best.

**Comment by digitarald** [comment]
> I thought about that, but since it's kind of a semantic mistake on their part.

+1, 🚫 is the right icon here, confirmed by [nounproject](https://thenounproject.com/search/?q=blocked).

> My gut feeling was just the icon.

WFM, also less severe as blocked resources are interesting but not always important.

**Comment by darkwing** [comment]
I like "blocked" text -- an "x" icon only doesn't convey much meeting -- I would probably see it as "canceled" or something.  The shield icon would be good too.

**Comment by violasong** [comment]
I like the idea of "blocked" text in the transfer column (regardless of what the other UI ends up being). 

I had been thinking we could overload the shield metaphor, but I guess we want to avoid muddling the tracking protection brand. 🚫 does seem good to me! The exclamation mark makes me think that something's wrong, e.g. the user should be warned. But this is more of a reassurance/notification that we stopped something bad from happening. I'm guessing it will look a bit nicer to have the icon replace the badge instead of being part of a badge, as the latter looks a little strange to me.

Red 60 seems good for the icon color, but I'd like to keep a darker shade for the text to match Console's --console-error-color. (For me, red 60 is a neon red that's uncomfortable to read due to the saturation. I can see why main Firefox can need this effect, but DevTools has a lot of errors so the errors need to chill out a bit :))

**Comment by digitarald** [comment]
> I like the idea of "blocked" text in the transfer column (regardless of what the other UI ends up being).

A blocked label somewhere makes sense, as we also have a reason to show with that.

> I'm guessing it will look a bit nicer to have the icon replace the badge instead of being part of a badge, as the latter looks a little strange to me.

That sounds good. Could you have a quick mock up? Also, I make my mockups intentionally strange to stir up discussions ;)

**Comment by violasong** [comment]
Could look something like this (icons lined up with the status text; would look better if we added a bit more side padding to the columns)

<img width="453" alt="Frame(3)" src="https://user-images.githubusercontent.com/55994/62170485-5c272b00-b2e0-11e9-9015-a63263704dab.png">

>Also, I make my mockups intentionally strange to stir up discussions ;)

:D It was a good idea to explore!

**Comment by digitarald** [comment]
> Could look better if we added a bit more side padding to the columns

Could you clarify? Space is the biggest constraint in Network resource table.

**Comment by fvsch** [comment]
Yeah space is in short supply in that table ^^
We currently use 4px of `padding-left`, and that's the whole separation between two columns' text. We could possibly go up to 6px (total cost = 16px) or 8px (total cost = 32px).

If the main issue is that the status badges are a bit too close to the left edge, we can perhaps shift them a bit:

```
.request-list-item .status-code {
    margin-inline-start: 2px;
}
```

Which looks like:

![screenshot](https://user-images.githubusercontent.com/243601/62195157-ac070000-b37b-11e9-9926-2ef96b38ee70.png)

**Comment by digitarald** [comment]
Curious what people think: Sould the spacing discussion block the blocked-resource discussion, or could we carry the results over to a bug which @darkwing and I can then prioritize?

**Comment by darkwing** [comment]
I think spacing should be a separate bug from the icon itself, though both would likely be quick to implement.

**Comment by violasong** [comment]
I agree about separate bug - totally a classic designer tangent :D - but yes, I was thinking it would not cost more space overall, but rather be a redistribution like in Florens' great screenshot, which also has very nice widths for columns that I'm not seeing in my (more default) Network. (I'd love to continue to tweak the default Network column sizes, though I know there's already been a lot of improvement here.)

**Comment by violasong** [comment]
(Correction - I just looked at Network on a fresh profile and the column sizing does look like Floren's screenshot - it's just a smaller screen size than what I use and it looks nicer. It's looking great! Maybe I'd just suggest slightly more width for the Size and slightly less width for Transferred/Cause, but at this point it's getting very minor and we should perhaps be asking some chrome parity questions instead. They don't seem to have Method or Transferred columns.)

New bug filed: https://github.com/firefox-devtools/ux/issues/87

**Comment by digitarald** [comment]
Continued in [implementation bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1570819)

**Comment by digitarald** [comment]
@fvsch thanks for re-opening this. I was hoping we positioned the icon far away from the danger zone, but it maks sense that it still triggers the icon muscle memory. Guess that icon is tainted now for anything interactive.

I'd be for a fully filled stop sign or a `forbidden` variation like https://thenounproject.com/search/?q=forbidden&i=2688625

**Comment by violasong** [comment]
The stop sign makes me think recording will be paused, so I have a preference for the forbidden variation linked above.

(The behavior of the Blocked or Search icons opening a sidebar that's far away feels a bit odd in general - maybe we can consider moving those to the left side at some point)
